FROM node:25-bookworm-slim

WORKDIR /app

COPY ./package.json ./package.json
COPY ./package-lock.json ./package-lock.json
COPY ./docker-entrypoint.ssr.sh /usr/local/bin/docker-entrypoint.ssr.sh
RUN mkdir -p /app/dist /app/node_modules
RUN npm ci

ENTRYPOINT ["docker-entrypoint.ssr.sh"]
