services:
  nginx:
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile.stg

  go:
    build:
      context: ./backend/
      dockerfile: ./Dockerfile.app

  ssr:
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile.ssr
