// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ArticlesColumns holds the columns for the "articles" table.
	ArticlesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true},
		{Name: "title", Type: field.TypeString, Size: 255},
		{Name: "body", Type: field.TypeString, Size: 2147483647},
		{Name: "is_published", Type: field.TypeBool, Default: false},
		{Name: "publish_start_at", Type: field.TypeTime, Nullable: true},
		{Name: "publish_end_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// ArticlesTable holds the schema information for the "articles" table.
	ArticlesTable = &schema.Table{
		Name:       "articles",
		Columns:    ArticlesColumns,
		PrimaryKey: []*schema.Column{ArticlesColumns[0]},
	}
	// CategoriesColumns holds the columns for the "categories" table.
	CategoriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true, Size: 64},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// CategoriesTable holds the schema information for the "categories" table.
	CategoriesTable = &schema.Table{
		Name:       "categories",
		Columns:    CategoriesColumns,
		PrimaryKey: []*schema.Column{CategoriesColumns[0]},
	}
	// CommentsColumns holds the columns for the "comments" table.
	CommentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true},
		{Name: "author_name", Type: field.TypeString, Size: 64},
		{Name: "body", Type: field.TypeString, Size: 2147483647},
		{Name: "is_visible", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "article_id", Type: field.TypeUint32},
	}
	// CommentsTable holds the schema information for the "comments" table.
	CommentsTable = &schema.Table{
		Name:       "comments",
		Columns:    CommentsColumns,
		PrimaryKey: []*schema.Column{CommentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "comments_articles_comments",
				Columns:    []*schema.Column{CommentsColumns[6]},
				RefColumns: []*schema.Column{ArticlesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "comment_article_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{CommentsColumns[6], CommentsColumns[4]},
			},
		},
	}
	// ArticleCategoriesColumns holds the columns for the "article_categories" table.
	ArticleCategoriesColumns = []*schema.Column{
		{Name: "article_id", Type: field.TypeUint32},
		{Name: "category_id", Type: field.TypeUint32},
	}
	// ArticleCategoriesTable holds the schema information for the "article_categories" table.
	ArticleCategoriesTable = &schema.Table{
		Name:       "article_categories",
		Columns:    ArticleCategoriesColumns,
		PrimaryKey: []*schema.Column{ArticleCategoriesColumns[0], ArticleCategoriesColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "article_categories_article_id",
				Columns:    []*schema.Column{ArticleCategoriesColumns[0]},
				RefColumns: []*schema.Column{ArticlesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "article_categories_category_id",
				Columns:    []*schema.Column{ArticleCategoriesColumns[1]},
				RefColumns: []*schema.Column{CategoriesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ArticlesTable,
		CategoriesTable,
		CommentsTable,
		ArticleCategoriesTable,
	}
)

func init() {
	ArticlesTable.Annotation = &entsql.Annotation{
		Table: "articles",
	}
	CategoriesTable.Annotation = &entsql.Annotation{
		Table: "categories",
	}
	CommentsTable.ForeignKeys[0].RefTable = ArticlesTable
	CommentsTable.Annotation = &entsql.Annotation{
		Table: "comments",
	}
	ArticleCategoriesTable.ForeignKeys[0].RefTable = ArticlesTable
	ArticleCategoriesTable.ForeignKeys[1].RefTable = CategoriesTable
}
