// Code generated by ent, DO NOT EDIT.

package article

import (
	"blog/internal/db/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id uint32) predicate.Article {
	return predicate.Article(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint32) predicate.Article {
	return predicate.Article(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint32) predicate.Article {
	return predicate.Article(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint32) predicate.Article {
	return predicate.Article(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint32) predicate.Article {
	return predicate.Article(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint32) predicate.Article {
	return predicate.Article(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint32) predicate.Article {
	return predicate.Article(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint32) predicate.Article {
	return predicate.Article(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint32) predicate.Article {
	return predicate.Article(sql.FieldLTE(FieldID, id))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Article {
	return predicate.Article(sql.FieldEQ(FieldTitle, v))
}

// BodyMarkdown applies equality check predicate on the "body_markdown" field. It's identical to BodyMarkdownEQ.
func BodyMarkdown(v string) predicate.Article {
	return predicate.Article(sql.FieldEQ(FieldBodyMarkdown, v))
}

// BodyHTML applies equality check predicate on the "body_html" field. It's identical to BodyHTMLEQ.
func BodyHTML(v string) predicate.Article {
	return predicate.Article(sql.FieldEQ(FieldBodyHTML, v))
}

// IsPublished applies equality check predicate on the "is_published" field. It's identical to IsPublishedEQ.
func IsPublished(v bool) predicate.Article {
	return predicate.Article(sql.FieldEQ(FieldIsPublished, v))
}

// PublishStartAt applies equality check predicate on the "publish_start_at" field. It's identical to PublishStartAtEQ.
func PublishStartAt(v time.Time) predicate.Article {
	return predicate.Article(sql.FieldEQ(FieldPublishStartAt, v))
}

// PublishEndAt applies equality check predicate on the "publish_end_at" field. It's identical to PublishEndAtEQ.
func PublishEndAt(v time.Time) predicate.Article {
	return predicate.Article(sql.FieldEQ(FieldPublishEndAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Article {
	return predicate.Article(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Article {
	return predicate.Article(sql.FieldEQ(FieldUpdatedAt, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Article {
	return predicate.Article(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Article {
	return predicate.Article(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Article {
	return predicate.Article(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Article {
	return predicate.Article(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Article {
	return predicate.Article(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Article {
	return predicate.Article(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Article {
	return predicate.Article(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Article {
	return predicate.Article(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Article {
	return predicate.Article(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Article {
	return predicate.Article(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Article {
	return predicate.Article(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Article {
	return predicate.Article(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Article {
	return predicate.Article(sql.FieldContainsFold(FieldTitle, v))
}

// BodyMarkdownEQ applies the EQ predicate on the "body_markdown" field.
func BodyMarkdownEQ(v string) predicate.Article {
	return predicate.Article(sql.FieldEQ(FieldBodyMarkdown, v))
}

// BodyMarkdownNEQ applies the NEQ predicate on the "body_markdown" field.
func BodyMarkdownNEQ(v string) predicate.Article {
	return predicate.Article(sql.FieldNEQ(FieldBodyMarkdown, v))
}

// BodyMarkdownIn applies the In predicate on the "body_markdown" field.
func BodyMarkdownIn(vs ...string) predicate.Article {
	return predicate.Article(sql.FieldIn(FieldBodyMarkdown, vs...))
}

// BodyMarkdownNotIn applies the NotIn predicate on the "body_markdown" field.
func BodyMarkdownNotIn(vs ...string) predicate.Article {
	return predicate.Article(sql.FieldNotIn(FieldBodyMarkdown, vs...))
}

// BodyMarkdownGT applies the GT predicate on the "body_markdown" field.
func BodyMarkdownGT(v string) predicate.Article {
	return predicate.Article(sql.FieldGT(FieldBodyMarkdown, v))
}

// BodyMarkdownGTE applies the GTE predicate on the "body_markdown" field.
func BodyMarkdownGTE(v string) predicate.Article {
	return predicate.Article(sql.FieldGTE(FieldBodyMarkdown, v))
}

// BodyMarkdownLT applies the LT predicate on the "body_markdown" field.
func BodyMarkdownLT(v string) predicate.Article {
	return predicate.Article(sql.FieldLT(FieldBodyMarkdown, v))
}

// BodyMarkdownLTE applies the LTE predicate on the "body_markdown" field.
func BodyMarkdownLTE(v string) predicate.Article {
	return predicate.Article(sql.FieldLTE(FieldBodyMarkdown, v))
}

// BodyMarkdownContains applies the Contains predicate on the "body_markdown" field.
func BodyMarkdownContains(v string) predicate.Article {
	return predicate.Article(sql.FieldContains(FieldBodyMarkdown, v))
}

// BodyMarkdownHasPrefix applies the HasPrefix predicate on the "body_markdown" field.
func BodyMarkdownHasPrefix(v string) predicate.Article {
	return predicate.Article(sql.FieldHasPrefix(FieldBodyMarkdown, v))
}

// BodyMarkdownHasSuffix applies the HasSuffix predicate on the "body_markdown" field.
func BodyMarkdownHasSuffix(v string) predicate.Article {
	return predicate.Article(sql.FieldHasSuffix(FieldBodyMarkdown, v))
}

// BodyMarkdownEqualFold applies the EqualFold predicate on the "body_markdown" field.
func BodyMarkdownEqualFold(v string) predicate.Article {
	return predicate.Article(sql.FieldEqualFold(FieldBodyMarkdown, v))
}

// BodyMarkdownContainsFold applies the ContainsFold predicate on the "body_markdown" field.
func BodyMarkdownContainsFold(v string) predicate.Article {
	return predicate.Article(sql.FieldContainsFold(FieldBodyMarkdown, v))
}

// BodyHTMLEQ applies the EQ predicate on the "body_html" field.
func BodyHTMLEQ(v string) predicate.Article {
	return predicate.Article(sql.FieldEQ(FieldBodyHTML, v))
}

// BodyHTMLNEQ applies the NEQ predicate on the "body_html" field.
func BodyHTMLNEQ(v string) predicate.Article {
	return predicate.Article(sql.FieldNEQ(FieldBodyHTML, v))
}

// BodyHTMLIn applies the In predicate on the "body_html" field.
func BodyHTMLIn(vs ...string) predicate.Article {
	return predicate.Article(sql.FieldIn(FieldBodyHTML, vs...))
}

// BodyHTMLNotIn applies the NotIn predicate on the "body_html" field.
func BodyHTMLNotIn(vs ...string) predicate.Article {
	return predicate.Article(sql.FieldNotIn(FieldBodyHTML, vs...))
}

// BodyHTMLGT applies the GT predicate on the "body_html" field.
func BodyHTMLGT(v string) predicate.Article {
	return predicate.Article(sql.FieldGT(FieldBodyHTML, v))
}

// BodyHTMLGTE applies the GTE predicate on the "body_html" field.
func BodyHTMLGTE(v string) predicate.Article {
	return predicate.Article(sql.FieldGTE(FieldBodyHTML, v))
}

// BodyHTMLLT applies the LT predicate on the "body_html" field.
func BodyHTMLLT(v string) predicate.Article {
	return predicate.Article(sql.FieldLT(FieldBodyHTML, v))
}

// BodyHTMLLTE applies the LTE predicate on the "body_html" field.
func BodyHTMLLTE(v string) predicate.Article {
	return predicate.Article(sql.FieldLTE(FieldBodyHTML, v))
}

// BodyHTMLContains applies the Contains predicate on the "body_html" field.
func BodyHTMLContains(v string) predicate.Article {
	return predicate.Article(sql.FieldContains(FieldBodyHTML, v))
}

// BodyHTMLHasPrefix applies the HasPrefix predicate on the "body_html" field.
func BodyHTMLHasPrefix(v string) predicate.Article {
	return predicate.Article(sql.FieldHasPrefix(FieldBodyHTML, v))
}

// BodyHTMLHasSuffix applies the HasSuffix predicate on the "body_html" field.
func BodyHTMLHasSuffix(v string) predicate.Article {
	return predicate.Article(sql.FieldHasSuffix(FieldBodyHTML, v))
}

// BodyHTMLEqualFold applies the EqualFold predicate on the "body_html" field.
func BodyHTMLEqualFold(v string) predicate.Article {
	return predicate.Article(sql.FieldEqualFold(FieldBodyHTML, v))
}

// BodyHTMLContainsFold applies the ContainsFold predicate on the "body_html" field.
func BodyHTMLContainsFold(v string) predicate.Article {
	return predicate.Article(sql.FieldContainsFold(FieldBodyHTML, v))
}

// IsPublishedEQ applies the EQ predicate on the "is_published" field.
func IsPublishedEQ(v bool) predicate.Article {
	return predicate.Article(sql.FieldEQ(FieldIsPublished, v))
}

// IsPublishedNEQ applies the NEQ predicate on the "is_published" field.
func IsPublishedNEQ(v bool) predicate.Article {
	return predicate.Article(sql.FieldNEQ(FieldIsPublished, v))
}

// PublishStartAtEQ applies the EQ predicate on the "publish_start_at" field.
func PublishStartAtEQ(v time.Time) predicate.Article {
	return predicate.Article(sql.FieldEQ(FieldPublishStartAt, v))
}

// PublishStartAtNEQ applies the NEQ predicate on the "publish_start_at" field.
func PublishStartAtNEQ(v time.Time) predicate.Article {
	return predicate.Article(sql.FieldNEQ(FieldPublishStartAt, v))
}

// PublishStartAtIn applies the In predicate on the "publish_start_at" field.
func PublishStartAtIn(vs ...time.Time) predicate.Article {
	return predicate.Article(sql.FieldIn(FieldPublishStartAt, vs...))
}

// PublishStartAtNotIn applies the NotIn predicate on the "publish_start_at" field.
func PublishStartAtNotIn(vs ...time.Time) predicate.Article {
	return predicate.Article(sql.FieldNotIn(FieldPublishStartAt, vs...))
}

// PublishStartAtGT applies the GT predicate on the "publish_start_at" field.
func PublishStartAtGT(v time.Time) predicate.Article {
	return predicate.Article(sql.FieldGT(FieldPublishStartAt, v))
}

// PublishStartAtGTE applies the GTE predicate on the "publish_start_at" field.
func PublishStartAtGTE(v time.Time) predicate.Article {
	return predicate.Article(sql.FieldGTE(FieldPublishStartAt, v))
}

// PublishStartAtLT applies the LT predicate on the "publish_start_at" field.
func PublishStartAtLT(v time.Time) predicate.Article {
	return predicate.Article(sql.FieldLT(FieldPublishStartAt, v))
}

// PublishStartAtLTE applies the LTE predicate on the "publish_start_at" field.
func PublishStartAtLTE(v time.Time) predicate.Article {
	return predicate.Article(sql.FieldLTE(FieldPublishStartAt, v))
}

// PublishStartAtIsNil applies the IsNil predicate on the "publish_start_at" field.
func PublishStartAtIsNil() predicate.Article {
	return predicate.Article(sql.FieldIsNull(FieldPublishStartAt))
}

// PublishStartAtNotNil applies the NotNil predicate on the "publish_start_at" field.
func PublishStartAtNotNil() predicate.Article {
	return predicate.Article(sql.FieldNotNull(FieldPublishStartAt))
}

// PublishEndAtEQ applies the EQ predicate on the "publish_end_at" field.
func PublishEndAtEQ(v time.Time) predicate.Article {
	return predicate.Article(sql.FieldEQ(FieldPublishEndAt, v))
}

// PublishEndAtNEQ applies the NEQ predicate on the "publish_end_at" field.
func PublishEndAtNEQ(v time.Time) predicate.Article {
	return predicate.Article(sql.FieldNEQ(FieldPublishEndAt, v))
}

// PublishEndAtIn applies the In predicate on the "publish_end_at" field.
func PublishEndAtIn(vs ...time.Time) predicate.Article {
	return predicate.Article(sql.FieldIn(FieldPublishEndAt, vs...))
}

// PublishEndAtNotIn applies the NotIn predicate on the "publish_end_at" field.
func PublishEndAtNotIn(vs ...time.Time) predicate.Article {
	return predicate.Article(sql.FieldNotIn(FieldPublishEndAt, vs...))
}

// PublishEndAtGT applies the GT predicate on the "publish_end_at" field.
func PublishEndAtGT(v time.Time) predicate.Article {
	return predicate.Article(sql.FieldGT(FieldPublishEndAt, v))
}

// PublishEndAtGTE applies the GTE predicate on the "publish_end_at" field.
func PublishEndAtGTE(v time.Time) predicate.Article {
	return predicate.Article(sql.FieldGTE(FieldPublishEndAt, v))
}

// PublishEndAtLT applies the LT predicate on the "publish_end_at" field.
func PublishEndAtLT(v time.Time) predicate.Article {
	return predicate.Article(sql.FieldLT(FieldPublishEndAt, v))
}

// PublishEndAtLTE applies the LTE predicate on the "publish_end_at" field.
func PublishEndAtLTE(v time.Time) predicate.Article {
	return predicate.Article(sql.FieldLTE(FieldPublishEndAt, v))
}

// PublishEndAtIsNil applies the IsNil predicate on the "publish_end_at" field.
func PublishEndAtIsNil() predicate.Article {
	return predicate.Article(sql.FieldIsNull(FieldPublishEndAt))
}

// PublishEndAtNotNil applies the NotNil predicate on the "publish_end_at" field.
func PublishEndAtNotNil() predicate.Article {
	return predicate.Article(sql.FieldNotNull(FieldPublishEndAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Article {
	return predicate.Article(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Article {
	return predicate.Article(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Article {
	return predicate.Article(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Article {
	return predicate.Article(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Article {
	return predicate.Article(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Article {
	return predicate.Article(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Article {
	return predicate.Article(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Article {
	return predicate.Article(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Article {
	return predicate.Article(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Article {
	return predicate.Article(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Article {
	return predicate.Article(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Article {
	return predicate.Article(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Article {
	return predicate.Article(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Article {
	return predicate.Article(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Article {
	return predicate.Article(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Article {
	return predicate.Article(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasCategories applies the HasEdge predicate on the "categories" edge.
func HasCategories() predicate.Article {
	return predicate.Article(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, CategoriesTable, CategoriesPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCategoriesWith applies the HasEdge predicate on the "categories" edge with a given conditions (other predicates).
func HasCategoriesWith(preds ...predicate.Category) predicate.Article {
	return predicate.Article(func(s *sql.Selector) {
		step := newCategoriesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasComments applies the HasEdge predicate on the "comments" edge.
func HasComments() predicate.Article {
	return predicate.Article(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, CommentsTable, CommentsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCommentsWith applies the HasEdge predicate on the "comments" edge with a given conditions (other predicates).
func HasCommentsWith(preds ...predicate.Comment) predicate.Article {
	return predicate.Article(func(s *sql.Selector) {
		step := newCommentsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Article) predicate.Article {
	return predicate.Article(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Article) predicate.Article {
	return predicate.Article(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Article) predicate.Article {
	return predicate.Article(sql.NotPredicates(p))
}
