include /etc/nginx/snippets/upstream.conf;

map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
}

server {
    listen 8000;

    include /etc/nginx/snippets/header.conf;

    location ~ ^/(@vite/|src/|node_modules/|__vite_ping$) {
        proxy_pass http://vite-dev:5173;
        include /etc/nginx/snippets/proxy.conf;
    }

    location ~* \.(png|jpe?g)$ {
        proxy_pass http://vite-dev:5173;
        include /etc/nginx/snippets/proxy.conf;
    }

    location /__vite_ws {
        proxy_pass http://vite-dev:5173;
        include /etc/nginx/snippets/proxy.conf;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
    }

    location / {
        proxy_pass http://go;
        include /etc/nginx/snippets/proxy.conf;
    }
}
