include /etc/nginx/snippets/upstream.conf;

server {
    listen 8000;

    set $csp_connect_src "'self'";
    include /etc/nginx/snippets/header.conf;

    proxy_intercept_errors on;
    error_page 418 =500 /error;

    root /usr/share/nginx/html/;

    location = /error {
        try_files /dist/client/src/error/error.html =404;
    }
    
    location /dist/client/ {
        try_files $uri $uri/ =404;
    }

    location / {
        proxy_pass http://go;
        include /etc/nginx/snippets/proxy.conf;
    }
}
